import * as THREE from 'three';
import {introScenes} from '../intro/scenes';
import {prepareSeoulStreet} from '../intro/SeoulStreet';
import {disposeObject} from '../intro/CinematicPlayer';
import {createComposer,disposeComposer} from '../fx/postprocessing';
export async function mountIntroViewer(host:HTMLElement){
 host.innerHTML='<div class="workspace"><div class="stage"></div><aside class="panel"><h2>인트로 뷰어</h2><button id="fullIntro">전체 인트로 재생 / 장면 검토 전환</button><label>장면<select id="scene"></select></label><div class="row"><button id="play">일시정지</button><button id="restart">장면 처음</button></div><label>장면 시간<input id="time" type="range" min="0" step=".01" value="0"></label><div class="status" id="introStatus">서울 지도 로딩 중…</div><p>현재 게임의 인트로 장면과 서울 스타일·기기 시간을 사용합니다. 전체 인트로 재생으로 전환하면 게임과 동일한 자막과 사운드도 확인할 수 있습니다.</p></aside></div>';
 await prepareSeoulStreet();const stage=host.querySelector<HTMLElement>('.stage')!,select=host.querySelector<HTMLSelectElement>('#scene')!,time=host.querySelector<HTMLInputElement>('#time')!,status=host.querySelector<HTMLElement>('#introStatus')!;
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(55,1,.1,5000),ctx={scene,camera};const composer=createComposer(renderer,scene,camera),scenes=introScenes();scenes.forEach((s,i)=>select.add(new Option(`${i+1}. ${s.name} · ${s.duration}초`,String(i))));
 let full:HTMLIFrameElement|undefined;
 host.querySelector<HTMLButtonElement>('#fullIntro')!.onclick=()=>{if(full){full.remove();full=undefined;}else{full=document.createElement('iframe');full.title='인트로 전체 재생';full.src='/tools/intro-player.html';full.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:2';stage.append(full);}host.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement>('#scene,#play,#restart,#time').forEach(el=>el.disabled=!!full);};
 let current=0,t=0,playing=true,frame=0;function clear(){scenes[current].dispose?.(ctx);for(const o of [...scene.children]){disposeObject(o);scene.remove(o);}scene.userData={};scene.fog=null;}
 function build(i:number){clear();current=i;t=0;scenes[i].build(ctx);time.max=String(scenes[i].duration);}select.onchange=()=>build(+select.value);host.querySelector<HTMLButtonElement>('#restart')!.onclick=()=>build(current);host.querySelector<HTMLButtonElement>('#play')!.onclick=()=>{playing=!playing;host.querySelector('#play')!.textContent=playing?'일시정지':'재생';};time.oninput=()=>{if(+time.value<t){const target=+time.value;build(current);t=target;}else t=+time.value;};
 const resize=new ResizeObserver(()=>{const w=stage.clientWidth,h=stage.clientHeight;if(w&&h){renderer.setSize(w,h);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}});resize.observe(stage);build(0);const clock=new THREE.Clock();function render(){const dt=Math.min(.05,clock.getDelta());if(playing&&!full)t=Math.min(scenes[current].duration,t+dt);scenes[current].update(t,playing?dt:0,ctx);time.value=String(t);status.textContent=`${scenes[current].name} · ${t.toFixed(1)} / ${scenes[current].duration}초`;if(!full)composer.render();frame=requestAnimationFrame(render);}render();return()=>{cancelAnimationFrame(frame);resize.disconnect();clear();disposeComposer(composer);renderer.dispose();};
}
