import {confirmDiscard} from './navigation';
import type {MissionSpecV2} from '../game/missionV2';
import {goals,goalNames,deployments,roles,validateMission} from './missionSchema';
const labels:Record<string,string>={count:'수량',hp:'개체 체력',role:'플라즈모이드 종류',spawnRadius:'스폰 반경 (m)',bossHp:'보스 체력',totalHp:'총 체력',unitHp:'개체 체력',concurrentCap:'동시 투입 상한',reinforceInterval:'증원 간격 (초)',projections:'보스 투영 수',groups:'보스 그룹 수',units:'투입 유닛',escort:'보스 호위',phases:'전투 페이즈',deploy:'투입 구성',afterSec:'투입 시각 (초, 없으면 이전 페이즈 전멸 후)',seconds:'생존 시간 (초)',hold:'유지 시간 (초)',targets:'동시 관측 대상 수',target:'방어 대상',respawns:'리스폰 허용 수 (-1 무제한)',timeLimit:'시간 제한 (초, 0 무제한)',maxBuildingLoss:'건물 손실 한도 (0 미사용)',maxLandmarkLoss:'랜드마크 손실 한도 (0 미사용)',shield:'피해 배율 (0~1)',formation:'진형',behavior:'행동',anchor:'호위 대상 유닛 번호 (0부터)',aggro:'주 공격 대상',buildingBrands:'건물 낙인 허용',offTargetPenalty:'비표적 처치 시간 차감',sweepPeriodMul:'파문 주기 배율',freqRegenMul:'주파수 회복 배율',leapChanceMul:'차원이동 확률 배율',leapCdMul:'차원이동 쿨다운 배율',zoneShrink:'작전 구역 축소',everySec:'축소 주기',step:'축소 거리',minRadius:'최소 반경',emit:'보스 증원 분출',interval:'분출 간격',ownSweep:'보스 중심 파문',healLink:'보스 회복 연결',range:'연결 거리',rate:'초당 회복량'};
const deployNames:Record<string,string>={roster:'종류·수량 직접 지정',pyramid:'단계적 증원',horde:'군집 증원',boss:'보스와 호위',phased:'다단계 전투',none:'적 없음'};
const enums:Record<string,Record<string,string>>={role:roles,target:{landmarks:'랜드마크',buildings:'일반 건물'},formation:{cluster:'밀집',ring:'포위',line:'전선'},behavior:{hunt:'추격',hold:'거점 유지',patrol:'순찰',escort:'호위'},aggro:{player:'플레이어',landmark:'랜드마크',building:'건물'}};
export async function mountMissionEditor(host:HTMLElement){
 host.innerHTML='<div class="mission"><aside class="list"><h2>단계별 미션</h2><button id="new">새 미션</button><button id="reload">서버 목록 다시 읽기</button><div id="missions"></div></aside><section class="form"><div class="row"><h2 id="heading">미션 편집</h2><button id="copy">복제</button><button id="save">서버에 저장</button></div><p>저장은 서버의 미션 원본에 즉시 반영됩니다. 이미 진행 중인 전투는 유지되며 다음 미션 진입부터 사용합니다. 기존 미션의 고급 설정도 보존합니다.</p><div class="status" id="saveStatus" role="status"></div><form id="missionForm"><div id="fields"></div></form></section></div>';
 const status=host.querySelector<HTMLElement>('#saveStatus')!,fields=host.querySelector<HTMLElement>('#fields')!,list=host.querySelector<HTMLElement>('#missions')!;
 const cities: {id:string;name:string}[]=await (await fetch('/maps/index.json')).json();let all:MissionSpecV2[]=[],revision='',token='',draft:any,create=false,dirty=false,dead=false;
 function notice(message:string){if(!dead)status.textContent=message;}
 function input(parent:HTMLElement,key:string,value:any,change:(v:any)=>void,options?:Record<string,string>){const label=document.createElement('label');label.textContent=labels[key]??key;const el=options?document.createElement('select'):typeof value==='boolean'?document.createElement('input'):document.createElement('input');
 if(el instanceof HTMLSelectElement){for(const [v,n] of Object.entries(options!))el.add(new Option(n,v));el.value=String(value);el.onchange=()=>{change(el.value);dirty=true;};}else {el.type=typeof value==='number'?'number':typeof value==='boolean'?'checkbox':'text';if(el.type==='checkbox')el.checked=value;else el.value=String(value??'');if(el.type==='number')el.step='any';el.oninput=()=>{change(el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?NaN:+el.value):el.value);dirty=true;};}label.append(el);parent.append(label);return el;}
 function tree(parent:HTMLElement,obj:any,key=''){const grid=document.createElement('div');grid.className='fields';parent.append(grid);for(const k of Object.keys(obj)){
  const value=obj[k];if(k==='model'||k==='type')continue;
  if(Array.isArray(value)){const box=document.createElement('fieldset');box.className='wide';const legend=document.createElement('legend');legend.textContent=labels[k]??k;box.append(legend);value.forEach((v:any,i:number)=>{const part=document.createElement('fieldset'),title=document.createElement('legend');title.textContent=`${i+1}`;part.append(title);tree(part,v,k);const remove=document.createElement('button');remove.type='button';remove.textContent='이 항목 제거';remove.onclick=()=>{value.splice(i,1);dirty=true;draw();};part.append(remove);box.append(part);});const add=document.createElement('button');add.type='button';add.textContent=k==='phases'?'페이즈 추가':'유닛 추가';add.onclick=()=>{value.push(k==='phases'?{deploy:structuredClone(deployments.roster)}:{role:'rusher',count:1,hp:1000});dirty=true;draw();};box.append(add);grid.append(box);}
  else if(value&&typeof value==='object'){const box=document.createElement('fieldset');box.className='wide';const legend=document.createElement('legend');legend.textContent=labels[k]??k;box.append(legend);if(k==='deploy')deployment(box,value,v=>obj[k]=v);else tree(box,value,k);grid.append(box);}
  else input(grid,k,value,v=>obj[k]=v,enums[k]);
 }
 if(key==='phases'&&obj.afterSec===undefined){const b=document.createElement('button');b.type='button';b.textContent='투입 시각 지정';b.onclick=()=>{obj.afterSec=30;dirty=true;draw();};grid.append(b);}}
 function deployment(parent:HTMLElement,obj:any,assign:(v:any)=>void){input(parent,'투입 방식',obj.model,v=>{assign(structuredClone(deployments[v]));dirty=true;draw();},keyDeploy(parent));tree(parent,obj);}
 function keyDeploy(parent:HTMLElement){return parent.closest('fieldset fieldset')?Object.fromEntries(Object.entries(deployNames).filter(([k])=>!['phased','none'].includes(k))):deployNames;}
 function draw(){fields.replaceChildren();const top=document.createElement('div');top.className='fields';fields.append(top);
 const id=input(top,'ID',draft.id,v=>draft.id=v) as HTMLInputElement;id.disabled=!create;id.required=true;
 const name=input(top,'미션 이름',draft.name,v=>draft.name=v) as HTMLInputElement;name.required=true;
 input(top,'단계 / 장 (0=공통)',draft.stage??0,v=>{if(v===0)delete draft.stage;else draft.stage=v;});input(top,'도시',draft.cityId??'',v=>{if(v)draft.cityId=v;else delete draft.cityId;},Object.fromEntries([['','모든 도시'],...cities.map(c=>[c.id,c.name])]));
 const label=document.createElement('label');label.className='wide';label.textContent='미션 설명';const brief=document.createElement('textarea');brief.value=draft.brief??'';brief.oninput=()=>{draft.brief=brief.value;dirty=true;};label.append(brief);top.append(label);
 input(top,'작전 반경 (m)',draft.zoneRadius,v=>draft.zoneRadius=v);
 const goal=document.createElement('fieldset');goal.innerHTML='<legend>미션 형태 / 승리 종료 조건</legend>';fields.append(goal);input(goal,'승리 조건',draft.goal.type,v=>{draft.goal=structuredClone(goals[v]);dirty=true;draw();},goalNames);tree(goal,draft.goal);
 const dep=document.createElement('fieldset');dep.innerHTML='<legend>플라즈모이드 투입</legend>';fields.append(dep);deployment(dep,draft.deploy,v=>draft.deploy=v);
 input(dep,'증원 종류 혼합',draft.spawnMix??'even',v=>draft.spawnMix=v,{even:'거머리·모기 혼합',rusher:'거머리',kiter:'모기'});
 const fail=document.createElement('fieldset');fail.innerHTML='<legend>실패 종료 조건</legend>';fields.append(fail);tree(fail,draft.fail);
 if(draft.modifiers){const mod=document.createElement('fieldset');mod.innerHTML='<legend>전장 특수 규칙</legend>';fields.append(mod);tree(mod,draft.modifiers);}
 notice(create?'새 미션 초안 · 저장하면 목록에 추가됩니다.':'저장 전 변경 사항을 확인하세요.');}
 async function select(m:MissionSpecV2,isNew=false){if(dirty&&!await confirmDiscard('저장하지 않은 변경 내용을 버릴까요?'))return;draft=structuredClone(m);create=isNew;dirty=false;draw();}
 function listing(){list.replaceChildren();const stages=[...new Set(all.map(m=>m.stage??0))].sort((a,b)=>a-b);for(const stage of stages){const h=document.createElement('h3');h.textContent=stage?`${stage}단계`:'공통 미션';list.append(h);for(const m of all.filter(m=>(m.stage??0)===stage)){const b=document.createElement('button');b.textContent=m.name;b.onclick=()=>select(m);list.append(b);}}}
 async function reload(){if(dirty&&!await confirmDiscard('변경 내용을 버리고 서버 목록을 읽을까요?'))return;notice('목록을 불러오는 중…');const response=await fetch('/api/editor/missions',{cache:'no-store'});if(!response.ok)throw new Error('편집 API에 연결할 수 없습니다. 개발 서버에서 실행하세요.');const data=await response.json();all=data.missions;revision=data.revision;token=data.token;dirty=false;listing();if(all[0])select(all[0]);}
 host.querySelector<HTMLButtonElement>('#new')!.onclick=()=>select({id:'mission-'+Date.now(),name:'새 미션',stage:1,goal:{type:'purge-all'},deploy:structuredClone(deployments.roster),fail:{respawns:3,timeLimit:300,maxBuildingLoss:0,maxLandmarkLoss:0},zoneRadius:2000} as MissionSpecV2,true);
 host.querySelector<HTMLButtonElement>('#copy')!.onclick=()=>{const copy=structuredClone(draft);copy.id+='-'+Date.now();copy.name+=' (복제)';select(copy,true);};host.querySelector<HTMLButtonElement>('#reload')!.onclick=()=>reload().catch(e=>notice(String(e)));
 host.querySelector<HTMLButtonElement>('#save')!.onclick=async()=>{const button=host.querySelector<HTMLButtonElement>('#save')!;if(!(host.querySelector('form') as HTMLFormElement).reportValidity())return;try{validateMission(draft,cities.map(c=>c.id));button.disabled=true;notice('서버에 저장 중…');const r=await fetch('/api/editor/missions',{method:'PUT',headers:{'Content-Type':'application/json','X-Editor-Token':token},body:JSON.stringify({mission:draft,revision,create})});const data=await r.json();if(!r.ok)throw new Error(data.error);all=data.missions;revision=data.revision;token=data.token;create=false;dirty=false;listing();draw();notice('저장 완료 · 다음 미션 진입부터 반영됩니다.');}catch(e){notice(String(e));}finally{button.disabled=false;}};
 const navigate=(e:Event)=>{if(dirty)(e as CustomEvent<{pending:Promise<boolean>[]}>).detail.pending.push(confirmDiscard('저장하지 않은 미션 변경 내용을 버리고 이동할까요?'));};host.addEventListener('studio-before-navigate',navigate);
 const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);try{await reload();}catch(error){notice(String(error));}return()=>{dead=true;host.removeEventListener('studio-before-navigate',navigate);window.removeEventListener('beforeunload',before);};
}
