import {it,expect,vi,afterEach} from 'vitest';
import {completeMapChunk,compactMapChunk} from '../src/world/CompleteMapChunk';
import {applyMapCorrections} from '../src/world/MapCorrections';
import {compiledStreetHeight} from '../src/world/CompiledStreet';
import {fetchWorldChunk} from '../src/world/mapLocator';
const input=()=>({raw:{cx:0,cz:0,terrain:{size:2,seaLevel:0,heights:[0,0,0,0]},objects:{buildings:[],roads:[],water:[]},underground:null},detail:null,appearance:null,roadGrade:{version:1,size:2,points:[],streetPlan:{version:1,region:'test',bounds:[0,0,1024,1024],origin:[0,0],sourceHash:'test',compilerVersion:'test',props:[],terrainHeights:[2,2,2,2],roadHeights:[2,2,2,2],resolvedBuildings:[],meshes:[{layer:3,position:[0,2,0,1024,2,0,0,2,1024],index:[0,2,1]}]}}} as any);
afterEach(()=>vi.unstubAllGlobals());
it('bakes support and geometry once, retains clean inputs and removes duplicated output fields',()=>{const source=input(),before=JSON.stringify(source),expected=compactMapChunk(applyMapCorrections([0,0],structuredClone(source.raw),structuredClone(source)));const c=completeMapChunk([0,0],source);expect(compactMapChunk(c)).toEqual(expected);expect(c.terrain.heights).toEqual([2,2,2,2]);expect(compiledStreetHeight(c.compiledStreet,20,20)).toBeCloseTo(2);expect(c.mapBuild?.input.roadGrade?.streetPlan).toBeUndefined();expect(c.mapBuild?.input.raw.terrain.heights).toEqual([0,0,0,0]);expect(JSON.stringify(source)).toBe(before);expect(applyMapCorrections([0,0],c,{detail:null,appearance:null,roadGrade:null})).toBe(c);expect(completeMapChunk([0,0],{raw:c,detail:null,appearance:null,roadGrade:null})).toBe(c);});
it('loads a standalone completed chunk with no correction-file requests',async()=>{const c=completeMapChunk([0,0],input()),fetcher=vi.fn(async()=>new Response(JSON.stringify(c)));vi.stubGlobal('fetch',fetcher);expect(await fetchWorldChunk([0,0],0,0,16,'https://test.invalid/')).toEqual(c);expect(fetcher).toHaveBeenCalledTimes(1);expect(String(fetcher.mock.calls[0][0])).toContain('maps/0/0/0_0/0_0.json');});
